### ISSUE TITLE
Calculation of the number of trashpoints in one area

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#101]
Calculation of the number of trashpoints in one area should be re-checked. Right now it is not possible to see the exact number of trashpoints for each country when zoomed out on world level.

**Comment by lynxlynxlynx** [comment]
A pretty useless number until bugs like #33 / #73 are fixed.

**Comment by lynxlynxlynx** [comment]
The proper counts are visible to the country admins, so this is a bit less important.

**Comment by kadry55** [comment]
Would be good to have superadmin seeing the same for all countries togerher as well - visualisation or export.

**Comment by lynxlynxlynx** [comment]
That stats component is likely reusable without much change, so it shouldn't be hard to add it atop the country list.

**Comment by lynxlynxlynx** [comment]
closing in favour of the more recent #329 .
