### ISSUE TITLE
App for other operation systems

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#102]
Blackberry, windows, etc.

**Comment by krishaamer** [comment]
We probably won't be able to do this unless there is a concerted effort by volunteers who really need another platform themselves. 99.6 percent of smartphones already run either Android or iOS (https://www.theverge.com/2017/2/16/14634656/android-ios-market-share-blackberry-2016)

Instagram and Facebook have approached this challenge by making some basic functionality available in the web-app so users from any platform can use the service from inside a browser.

@kadry55

**Comment by kadry55** [comment]
Results from Africa are following:

Huawei MT7-L09 | Android | 
iPhone 6 | IOS | 
Samsung | Android |   |   |  
Samsung Prime Galaxy | Android |   |   |  
Samsung J1 | Android |   |   |  
Tecno WS Lite | Android? |   |   |  
X-TIGI B310 | Android? |   |   |  
Samsung S7 | Android |   |   |  
Apple 6S/Samsung Galaxy J1 | IOS |   |   |  
Lenovo BL243 | Windows? |   |   |  
Blackberry Z10 | Blackberry? |   |   |  
Huawei P8 Lite | Android |   |   |  
Hisense (HSU91) | ? |   |   |  
Samsung S6 | Android |   |   |  
Samsung Galaxy | Android |   |   |  
Samsung J1 | Android |   |   |  
Samsung Sb | Android |   |   |  
Lenovo Tab | Windows? |   |   |  
iPhone 6 | IOS |   |   |  
iPhone 6 | IOS |   |   |  
iPhone 6 | IOS |   |   |  
Samsung Galaxy J1 | Android |   |   |  
HTC/iPhone 5 | IOS |   |   |  


Android | IOS | Not compatible?
47.83% | 26.09% | 26.09%

I agree, web app will solve the problem :)

**Comment by KristiinaKerge** [comment]
web lite should solve it
