### ISSUE TITLE
Export system for admin web

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#103]
Admin should be able to get an export:
1. dump
2. filter by time/date/country
3. filter by status

**Comment by kadry55** [comment]
One volunteer tried to solve this but got stuck. 
He would need information on how to make queries towards app database and parameters information would be good as well (he said he can get it from the source code if there is no doc about that). 
@rionita @lynxlynxlynx @krishaamer @iiasunshine Could you help?

**Comment by lynxlynxlynx** [comment]
the declaration: https://github.com/letsdoitworld/World-Cleanup-Day/blob/master/backend-api/api/v1.0.yaml

**Comment by lynxlynxlynx** [comment]
Just sorting the issue list by date of modification would be good enough.

**Comment by lynxlynxlynx** [comment]
This is done for the WWP, while admin web won't have this functionality.
