### ISSUE TITLE
Admin web - map loading is too slow (5s)

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#104]

**Comment by kadry55** [comment]
I think this should be a priority!!!

**Comment by kadry55** [comment]
When logged in, map is not loading (5min loading now)

**Comment by KristiinaKerge** [comment]
@lynxlynxlynx @iiasunshine @krishaamer @kirilind how long it takes to load the map https://app.worldcleanupday.com/

**Comment by kirilind** [comment]
takes me a few seconds in Chrome/OSX, however a speed test counted about 700ms from Sweden, but a lot more from US:
<img width="1103" alt="screen shot 2017-12-28 at 16 37 35" src="https://user-images.githubusercontent.com/4502647/34413647-6ff4b73a-ebed-11e7-8f3f-6deedce80c84.png">

**Comment by kadry55** [comment]
I tested as well and got 10s for the full loading of the data in https://www.webpagetest.org/: 

![image](https://user-images.githubusercontent.com/30211382/34482081-78aa211a-efbe-11e7-9d23-50d5725af324.png)

In pingdom website speed test i got results: 1,48s but it seems that it doesn't consist of the full data loading (as in reality i never saw trashpoints in less than 5s).

**Comment by kadry55** [comment]
@KristiinaKerge is there any update on this issue? The map and trashpoints are loading 20sec some days.

**Comment by kadry55** [comment]
Only Google Chrome, not Safari. Trashpoints/users loading is still too slow.

**Comment by KristiinaKerge** [comment]
we added more resources to it in Azure and it should be fixed now. May I close this issue @kadry55
