### ISSUE TITLE
[Admin Web] Zoom out the map for John Doe to City level instead of the street level

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#11]

**Comment by rionita** [comment]
When accessing https://app.worldcleanupday.com/ without being logged in, you are zoomed in to close detail.
See screenshots for current and desired zoom level.

![current zoom level](https://user-images.githubusercontent.com/4987893/33320662-a7204436-d44b-11e7-897c-d5d5f148dd37.png)
![desired zoom level](https://user-images.githubusercontent.com/4987893/33320663-a73e7af0-d44b-11e7-879a-079803cc4d71.png)

**Comment by KristiinaKerge** [comment]
@rionita how is going with this task

**Comment by kadry55** [comment]
Will this affect also the app view in John Doe - without signing in?

**Comment by KristiinaKerge** [comment]
Fixed in new version
[
![webapp](https://user-images.githubusercontent.com/26063413/42747542-81752612-88e5-11e8-8acc-ad8476e8fbff.jpg)
](url)
