### ISSUE TITLE
[Admin Web] Edit trashpoint - no pointer when changing location

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#113]
https://drive.google.com/open?id=0B-AbsGblifS-WWIwT2pNS0V1SWM

**Comment by krishaamer** [comment]
Developer comment regarding implementing the movement of the marker after changing location:
"Implemented hand only on drag, cursor otherwise. We can’t update the right hand map before saving, because the right hand map only shows persisted information
and it’s connected directly to the database, showing only the already saved trashpoints."

**Comment by krishaamer** [comment]
Improve UX of TP creation (when user clicks "Place Trashpoint") - something should happen.

- The pointer changes into a Pin and the user can place it where she wants on the map.
- Then the sidebar opens with more options and the address of the selected location

**Comment by kadry55** [comment]
When adding traspoint from Decimal coordinates and clicking on "Set", it should go to the coordinates location. Now it is remaining on the location of the user and cannot be double checked.

**Comment by KristiinaKerge** [comment]
@rionita can you please estimate it, we tested it during our meeting in Nov

**Comment by KristiinaKerge** [comment]
@kadry55 @lynxlynxlynx is it better in new version?

**Comment by kadry55** [comment]
Yes, location changes when clicking on spot.
