### ISSUE TITLE
[Admin Web] multiple admins for an area / country should be possible

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#116]
- Interface to assign super admins
-- Can do what they want (create other super admins)

- Multiple country admins
-- Can create area admins

- Multiple area admins
-- Can create sub-area admins (Bucharest area admin can create "Sector 1" admins, etc)

**Comment by lynxlynxlynx** [comment]
Actually with the rewrite, assigning the role to several users is now possible.
