### ISSUE TITLE
App not installable on some android phones

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#120]
App store: app is not compatible with phone
SW version: Android 4.3

**Comment by kadry55** [comment]
Samsung Galaxy Nexus 4.3; SW Android 4.3
SAMSUNG S7 COPY. Software version is 6.0.1.

**Comment by KristiinaKerge** [comment]
currently app requires Android 4.4 and up

**Comment by kadry55** [comment]
Mapping can be done by web app (should be ready by end if Jan)
