### ISSUE TITLE
App doesn’t keep users logged in

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#121]
feedback from  iOS user -  I have to relogin each time - a huge time cost;

**Comment by cleanappio** [comment]
same experience on iOS 11 -

**Comment by KristiinaKerge** [comment]
it seems to be only iOS problem

**Comment by KristiinaKerge** [comment]
iOS 11.2.6 keeps user logged in.
@cleanappio are you still facing this problem
