### ISSUE TITLE
Fail Whale error

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#122]
Report from Albania: Xiaomi redmi note, Android: Fail Whale comes up after every action.

**Comment by kadry55** [comment]
Kosovo has the same problem when logging in:  iphone 7

**Comment by krishaamer** [comment]
I get the same error in Estonia (iPhone 7)

**Comment by kadry55** [comment]
#106 Related to the question about requirements

**Comment by android-labtech** [comment]
The fail whale was with me on my mobile just yesterday afternoon, and also the web admin was server unreachable.

![screenshot_2018-03-10-19-00-16](https://user-images.githubusercontent.com/6918849/37248204-a248162a-24cb-11e8-9eed-1af337b897f8.png)
