### ISSUE TITLE
Admin web not opening 

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#125]
Map is not loading + not possible to log in.

**Comment by KristiinaKerge** [comment]
it is ok now, 12 dec

**Comment by kadry55** [comment]
Did we get a reason for that from logs?

**Comment by rionita** [comment]
no resolution on this. best person to investigate is Ciprian, but he is fully booked on another project.
We will see if he has some availability in January.

**Comment by KristiinaKerge** [comment]
do we know what caused it?
