### ISSUE TITLE
App asks user to add the pictures again but there's no option to do so

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#126]
![img_2729](https://user-images.githubusercontent.com/54409/34049872-dda0b320-e1b0-11e7-9439-245fed21ec8e.PNG)

Because the app doesn't allow uploading pictures from the gallery the only option would be to take the pictures again. But I have already moved to a different location because the app is so slow.

**Comment by KristiinaKerge** [comment]
how we can solve it @rionita @sebid @cprpopqual 
when this error message appears
@lynxlynxlynx @iiasunshine have you got this error :)
