### ISSUE TITLE
Re-locate button (locate me)

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#14]
Map should follow the user automatically

**Comment by kadry55** [comment]
@krishaamer Who could do that? Where should we place it in the roadmap?

**Comment by kadry55** [comment]
Duplicated with #55 : https://github.com/letsdoitworld/World-Cleanup-Day/issues/55

**Comment by KristiinaKerge** [comment]
from Kris: A "Locate me" button should be displayed on the map. When the user presses the button, the map is moved to the point where the current location of the user marker is displayed.

**Comment by KristiinaKerge** [comment]
In new version "Locate me" button is displayed on the map.
