### ISSUE TITLE
detect and fix not translatable parts

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#156]
[
![types not translated](https://user-images.githubusercontent.com/26063413/35848382-a3597a68-0b26-11e8-97b3-bb2f223c9554.jpg)
](url)

**Comment by KristiinaKerge** [comment]
The types are translated but doesn't appear in the app

**Comment by Dasha1990** [comment]
[Dutch] "Annuleren" is shown instead of translation for label_text_app_subtitle on welcome screen http://take.ms/q7gGH

**Comment by KristiinaKerge** [comment]
let's not include Dutch. We can't have mistake on the first screen

**Comment by Dasha1990** [comment]
[Estonian] Missing connection error message  label_error_network_text doesn't fit the screen  http://take.ms/Yeqfu

**Comment by Dasha1990** [comment]
[Albanian] Trash was captured screen. Text doesn't fit the screen  label_text_congrats_subtitle http://take.ms/4sQZL

**Comment by Dasha1990** [comment]
[Albanian] Trashpoint details. Text doesn't fit the screen  label_TP_updated_date http://take.ms/3i1Lr

**Comment by Dasha1990** [comment]
[Dutch] Trash was captured screen. Text doesn't fit the screen label_text_congrats_subtitle http://take.ms/N3Nq7

**Comment by lynxlynxlynx** [comment]
- It's not clear where it came from, but that Dutch Annuleren has been changed in the meanwhile.
- I can't find any code references to label_error_network_text, but the dialog should resize with the text.
- Albanian 1 & Dutch 2: just needs increasing the header size in mobile-app/src/screens/CreateMarker/components/CongratsModal/styles.js to around double.
- Albanian 2: this one will also hit many, but is trickier. Needs a designer's input.

**Comment by Dasha1990** [comment]
[All translations] Create event. Missing translations for trash types http://take.ms/E4wqP those translations were added to translations document label_trash_type_plastic and etc

**Comment by Dasha1990** [comment]
[Estonian] Trash was captured screen. Text doesn't fit the screen label_text_congrats_subtitle http://take.ms/PZQ2w

**Comment by Dasha1990** [comment]
[Estonian] Trashpoint details. Text doesn't fit the screen label_TP_updated_date http://take.ms/jM5H9

**Comment by Dasha1990** [comment]
[All translations] Select country screen. Missing translations fro Cancel/ Search buttons http://take.ms/QrvUD

**Comment by Dasha1990** [comment]
[Cebuano] Trash was captured screen. Text doesn't fit the screen label_text_congrats_subtitle; Trashpoint details. Text doesn't fit the screen label_TP_updated_date, label_TP_created_date http://take.ms/jfSkL

**Comment by Dasha1990** [comment]
[Filipino]  Missing connection error message label_error_network_text doesn't fit the screen, Trashpoint details. Text doesn't fit the screen label_TP_updated_date, label_TP_created_date http://take.ms/Ak62u

**Comment by Dasha1990** [comment]
[Belarussian]
Trashpoint details. Text doesn't fit the screen label_TP_updated_date;
Trash was captured screen. Text doesn't fit the screen label_text_congrats_subtitle; 
http://take.ms/Fpu8H

**Comment by lynxlynxlynx** [comment]
I've just merged the waste type fix and fixed the search/country one. The others are the same as the ones found before.

**Comment by Dasha1990** [comment]
[Ukrainian] Welcome screen merged privacy policy + terms of use http://take.ms/VY7Mo

**Comment by Dasha1990** [comment]
[Slovenian]  
Trashpoint details. Text doesn't fit the screen  label_TP_updated_date, label_TP_created_date ;
Trash was captured screen. Text doesn't fit the screen label_text_congrats_subtitle; 
http://take.ms/e7Ohe

**Comment by Dasha1990** [comment]
[All translations] Missing translation for title of Join other people who are mapping trash alert label_text_popover_subtitle http://take.ms/W74oR

**Comment by Dasha1990** [comment]
[Hungarian] 
Trashpoint details. Text doesn't fit the screen label_TP_updated_date, label_TP_created_date ;
Welcome screen merged privacy policy + terms of use 
http://take.ms/LG5eV

**Comment by Dasha1990** [comment]
[greek] Welcome screen merged privacy policy + terms of use label_privacy_policy_header label_header_tc http://take.ms/sDL6A

**Comment by Dasha1990** [comment]
[Turkish] Trashpoint details. Text doesn't fit the screen label_TP_updated_date, label_TP_created_date http://take.ms/Gw3Ch

**Comment by KristiinaKerge** [comment]
- [Dutch] "Annuleren" is shown instead of translation for label_text_app_subtitle on welcome screen http://take.ms/q7gGH - is this fixed?

- Jaka merged the waste type fix and fixed the search/country one - will it be used in release?

- all other issues - [Turkish], [greek] , [Hungarian],  Missing translation for title of Join other people who are mapping trash alert, [Slovenian], [Ukrainian], [Belarussian], [Filipino], [Cebuano], [Estonian], [Albanian] - ok to release with these issues. We will get better :)

**Comment by lynxlynxlynx** [comment]
Ok, a few more blind fixes are in:
- a few updated translations (including the Dutch)
- alert and congrats have more space
- a translation is used for label_text_popover_subtitle

**Comment by Dasha1990** [comment]
[Dutch] Annuleren is fixed;
[Create event] Waste type is fixed;
[ Select country screen]   Cancel/ Search buttons  are fixed

**Comment by Dasha1990** [comment]
[All translations] at viewing trashpoint details missing translation for waste's types http://take.ms/aD848 I guess that is still same labels  label_trash_type_plastic and etc

**Comment by lynxlynxlynx** [comment]
I see where it happens, more hardcoded strings. It's a bit odd, but I've pushed a fix.

**Comment by Dasha1990** [comment]
[Norwegian] I'm choosing Norsc bokmal (as I understand that's official Norway language) but there are no any translations shown in the app

**Comment by lynxlynxlynx** [comment]
Closing, remaining issues tracked in #207 and #208.
