### ISSUE TITLE
About page error

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#158]
![about page error](https://user-images.githubusercontent.com/26063413/35881827-c3fd4ce0-0b8a-11e8-8cbc-88a1e896fbf0.jpg)

**Comment by android-labtech** [comment]
The issue is: the page "About" don't scroll down, and there is the DUX
logo as displayed in the image, by clicking around it links to [https://dux.ee](url)
The OS on phone is Android 7.0.

**Comment by lynxlynxlynx** [comment]
worksforme on android.

**Comment by kadry55** [comment]
Works for me on android as well

**Comment by KristiinaKerge** [comment]
@krishaamer is it ok now?

**Comment by KristiinaKerge** [comment]
fixed
