### ISSUE TITLE
The trash size slider is not in the right place when editing [UX]

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#159]
Even though the trash size had been set to "Cartload" when editing the slider location is always set to "Handful". (Only the icon indicating the selection is correctly updated.)

See image:
![img_6035](https://user-images.githubusercontent.com/54409/36001809-63099662-0d30-11e8-9f0f-ff19a54288cf.PNG)

**Comment by lynxlynxlynx** [comment]
Seems to be limited to mobile apps — the backend editing is fine.

**Comment by KristiinaKerge** [comment]
fixed
