### ISSUE TITLE
clustering is not monotonous

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#166]
While zooming in, sometimes the same cluster gets broken up and rejoined, even though the zoom levels are only increasing.

Example at the belly of the beast:
![spectacle n15589](https://user-images.githubusercontent.com/121515/36639679-7ee52114-1a12-11e8-8406-e24c8eac1155.png)
![spectacle k15589](https://user-images.githubusercontent.com/121515/36639687-9d8c3a80-1a12-11e8-9409-e6dcdb82a257.png)
![spectacle q15589](https://user-images.githubusercontent.com/121515/36639688-ab813d34-1a12-11e8-9e2b-dfb69a57be06.png)
![spectacle s15589](https://user-images.githubusercontent.com/121515/36639695-b831dc0a-1a12-11e8-9191-ad67fe1c7380.png)
![spectacle h15589](https://user-images.githubusercontent.com/121515/36639705-e6d2f094-1a12-11e8-9323-3f4471d750ef.png)

**Comment by krishaamer** [comment]
Maybe this would work better? 
https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97

**Comment by lynxlynxlynx** [comment]
My case would be fixed by fixing #25 already (jumping from the first image to last with one click). I don't know if it happens in any other scenario.

So this is something to recheck after #25 is done and doesn't warrant separate attention.

**Comment by lynxlynxlynx** [comment]
This was fixed by the duplicate removal, closing for now.
