### ISSUE TITLE
Admin web - no trashpoints visible, cannot log in

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#167]
![image](https://user-images.githubusercontent.com/30211382/36725377-d027d726-1bbe-11e8-84db-f1e3479928d1.png)

**Comment by krishaamer** [comment]
@kadry55 Are you still experiencing this bug?

I just tried and now it seems to be working.

 
<img width="1676" alt="screen shot 2018-02-27 at 18 30 05" src="https://user-images.githubusercontent.com/54409/36740897-75a005b6-1bec-11e8-987a-72dbc17485bd.png">

**Comment by krishaamer** [comment]
Working again.
