### ISSUE TITLE
web-app: "Place trashpoint" button too narrow

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#168]
In Firefox 57 the space is 2px too narrow, so the button looks like this:
![image](https://user-images.githubusercontent.com/121515/36841773-b843e398-1d49-11e8-9d8b-fa016e6ae2e4.png)

It's a trivial fix in here:
https://github.com/letsdoitworld/World-Cleanup-Day/blob/5d2a91146554aa02cd881ec3e00a8ac64b116a69/web-app/src/routes/Home/Home.css#L65

Works without width set, but can be converted to min-width if something else is relying on it.

**Comment by pornpailin0328** [comment]
Aourt app
