### ISSUE TITLE
Question: is previous trashpoint status easy to extract from cleaned trashpoints?

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#169]
Trashpoints only have 4 statuses: threat, regular, cleaned, outdated.

For impact assessment, we need to be able to determine what kind of points were cleaned, once they are marked as such. Since there is no threat-cleaned and regular-cleaned statuses, how hard will it be to extract this data? Will it be available at all?

There's obviously more value in cleaning points that are threats.

Relates to #63 and a bit to #70.

... from the db dump it is obvious a _rev field is stored (couchdb internal), so it's just a question if the old revisions are (easily) resurrectable.

**Comment by pornpailin0328** [comment]
URL

**Comment by lynxlynxlynx** [comment]
Seems to be so, fortunately. :+1: 
https://pouchdb.com/api.html#fetch_document
