### ISSUE TITLE
web-app: only superadmins can block users

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#170]
Normal (country/area) admins should have the same right.

This function needs adapting:
https://github.com/letsdoitworld/World-Cleanup-Day/blob/a1e678de01269e897831475aea88b3084ee78713/web-app/src/pages/UserDetails/UserDetails.js#L126

**Comment by KristiinaKerge** [comment]
is it solved @lynxlynxlynx ?

**Comment by lynxlynxlynx** [comment]
no

**Comment by Dasha1990** [comment]
Country/area admins are able to block users now http://take.ms/tvnvQ
