### ISSUE TITLE
[Offline] Trashpoints are duplicated at saving in offline

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#189]
Device: Samsung S4 note 6.0.1
Preconditions:
App was created and builded from master branch
Steps to reproduce:

Login to the app
Turn connection off
Create several trashpoints
Turn connection on
Check requests

Result:
there is two same trashpoints created http://take.ms/Kl063

**Comment by lynxlynxlynx** [comment]
This is known behaviour, unless it always happens for you in offline mode. Just from #179 stats it is clear it happens 10-20% of the time.

**Comment by Dasha1990** [comment]
Let me check it again, but I three times get this behavior during saving several trashpoints from offline

**Comment by lynxlynxlynx** [comment]
There's probably an API consumption or emission issue underneath and everyone suffers the same. What I'm saying is that this shouldn't block offline, as it happens online too (tracked in separate bugs).

**Comment by Dasha1990** [comment]
got it, thank you for info!

**Comment by Dasha1990** [comment]
I've created two trashpoints in offline and after turning connection on eight trashpoints were saved http://take.ms/B9nGi ( some of them without images)

**Comment by lynxlynxlynx** [comment]
This has now been fixed and is ready for a retest.
