### ISSUE TITLE
App does not open - white screen loading 

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#190]
Tech Specs:

Huawai Mate 9 Dual SIM
Android EMUI 8.0.0

Just a white screen with the icon going around in circles in the middle of the page
I have installed, uninstalled, reinstalled four times from Google Play. When I click on INSTALL, it runs the upload. Then it asks if I want to launch. When I hit OPEN it asks if I want to allow location data. I click ALLOW and then the White Screen of Death with the loading circular thingie just going round and round.......

**Comment by KristiinaKerge** [comment]
After a software update on the phone the app loads correctly

**Comment by kadry55** [comment]
Same issue from another user (UK):

Huawei model number RIO-L01
Build Number: RIO-L01C432B431
EMUI version: EMUI 4.0.3
Android version: 6.0.1

**Comment by KristiinaKerge** [comment]
if there is a software update available he/she should install the update

**Comment by kadry55** [comment]
Phone is up to date

**Comment by kadry55** [comment]
2nd report: After a few minutes on the white screen, the app started functioning.
