### ISSUE TITLE
update terms and privacy doc

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#204]

**Comment by lynxlynxlynx** [comment]
Where are the new texts?

**Comment by KristiinaKerge** [comment]
https://drive.google.com/open?id=1X-H_MVZyIHCwBhXtKm8nN1beMHUleMziT7YOrYVyIns and https://drive.google.com/open?id=1qWhhSL8A2-2zg6Bnd-PyRZe4KV3ZScnupNMyPKR2cLg

**Comment by lynxlynxlynx** [comment]
These are final and will do for all the changes until the June release, right?

**Comment by KristiinaKerge** [comment]
yes

**Comment by KristiinaKerge** [comment]
https://app.worldcleanupday.com/privacy 
https://app.worldcleanupday.com/terms
