### ISSUE TITLE
i18n: add language variant support

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#207]
- [x] fix language variants overwriting each other (eg. pt_BR and pt_PT) by using full lang codes in crowdin.yml
  - [x] update enabled/disabled language list
  - [x] enable new languages that previously weren't possible (brazlian portuguese (pt_br), traditional chinese (zhtw), arabic sa (arsa))
- [x] recheck both Portuguese stopped overwriting each other in crowdin PRs
- [x] recheck Nynorsk works and that the translation isn't actually Bokmål

(defered until offline release)

**Comment by Dasha1990** [comment]
[All translations] Join other people pop up. Missing translation  for label_text_popover_subtitle http://take.ms/E4rsh
