### ISSUE TITLE
Server error 400 when zooming out

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#209]
I've received reports (and this has happened with me as well) during past week that server error 400 is happening regulary again.
For me it happens when i try to zoom out.
PS! NW connection is OK
![img_3730](https://user-images.githubusercontent.com/30211382/38185018-85f89996-3654-11e8-8381-198c18dce2a5.PNG)
![img_3729](https://user-images.githubusercontent.com/30211382/38185019-861569fe-3654-11e8-99b7-092ab53c25fd.PNG)

**Comment by KristiinaKerge** [comment]
fixed
