### ISSUE TITLE
[iOs] Can't login via FB

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#212]
Device: iPhone 6s+ 11.2.6
Preconditions:
App was created and builded from master branch
Steps to reproduce:

Open app
Login via FB
Check requests

Result:
there is no request for login 
http://take.ms/wympS 
can't reproduce on Android 
experienced on release iOs build

**Comment by lynxlynxlynx** [comment]
the request mentions google, that's odd.
