### ISSUE TITLE
Help with web implementation

### ISSUE THREAD

**Issue by luizbills** [letsdoitworld/World-Cleanup-Day#216]
I'm trying to create a functional map of World Cleanup Day to put on a website.

What I need understand to get trashpoints and add trashpoints?

I already have a valid token but I can not understand some things in the REST API docs.

- `PUT /trashpoints` requires a `trashpoint` object, but what is the scheme of this object?
- `POST /overview/trashpoints` requires a `query` object, but what is the scheme of this object?

Is there a more detailed documentation?

**Comment by lynxlynxlynx** [comment]
PUT is definitely the wrong choice — that's for sending data, uploading a trashpoint.

**Comment by lynxlynxlynx** [comment]
MapQuery is defined in the same file, but I now see the generated API docs don't display all the info:
```
  MapQuery:
    name: query
    in: body
    required: true
    schema:
      type: object
      required: [datasetId, rectangle]
      properties:
        datasetId:
          $ref: "#/definitions/UUID"
        rectangle:
          $ref: "#/definitions/GeoRectangle"
        cellSize:
          $ref: "#/definitions/GeoResolution"
        scale:
          $ref: "#/definitions/GeoScale"
```
The referenced definitions are visible at the end of the docs. There is currently only one datasetId and you can get it even without auth.

**Comment by luizbills** [comment]
@lynxlynxlynx Any plans to create a easy way to embed your map in another sites?

**Comment by lynxlynxlynx** [comment]
I don't know enough about react to do it myself, but my plan was to add an extra route to be able to just use an iframe centered around a different place than Estonia (default if geolocation is off). I managed that, but then it turned out zoom is also needed and other complications and I ran out of time. So help would be appreciated there.

**Comment by lynxlynxlynx** [comment]
It's an app, it doesn't really take query parameters or expose library objects that way (routes are like fake urls).

**Comment by luizbills** [comment]
But you can easily use your code to create a custom library and expose an object or just a function to initialize the map. A `<iframe>` will almost never be a good solution

**Comment by lynxlynxlynx** [comment]
iframes are easier for the users, but sure, direct implementations are nicer from a technical POW.

You say it's easily done — if you know someone, send him over, it's an open source project.

**Comment by luizbills** [comment]
I don't have experience with react. But I believe you can create a public interface to take advantage of all the code you already have done in the web-app.

If you really can not do this then we can close this issue.
