### ISSUE TITLE
Admin: cannot delete a trash

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#219]
Clicked on delete for several times - didn't work. Signal is good.

![image](https://user-images.githubusercontent.com/30211382/38698220-0a79ce88-3e9d-11e8-913b-6ad4233a6960.png)

**Comment by lynxlynxlynx** [comment]
Probably 500 errors. Can't reproduce right now as I get them when trying to create a test point as well.
