### ISSUE TITLE
Allow to place a spot on the map manually

### ISSUE THREAD

**Issue by bramanis** [letsdoitworld/World-Cleanup-Day#22]
If I navigate on the map, I should be allowed to place a pin on the map manually, without first pressing the "add" button. More intuitivity is rather good.

**Comment by kadry55** [comment]
The logic behind add button, is that:
a) you can place trashpoint only in 100m from your location
b) you need to make a photo in order to create the trashpoint (that's why you are taken to camera at first)

**Comment by KristiinaKerge** [comment]
in new version you can edit location by placing a spot to the map if you are in 100m radius of the location.
