### ISSUE TITLE
[UI] iPhone X issues

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#222]
**[Create trashpoint] User cannot see if he selected needed trashpoint type in offline mode** 
Device: iPhone X 11.2.6
Release build

Preconditions:
App was created and built from master branch
Steps to reproduce:
1. Login to the app
2. Turn connection off
3. Create trashpoint

Result: see the photo attached
![1 ui selection button 2018-04-23 13 59 19](https://user-images.githubusercontent.com/38650029/39122999-29d4ea00-46ff-11e8-9038-a4ed6f130d78.jpg)

**[Create trashpoint] Trash captured message is displayed weird**
Device: iPhone X 11.2.6
Preconditions:
App was created and builded from master branch
Steps to reproduce:
1. Login to the app
2. Turn connection off
3. Create trashpoint -> Add a photo by camera

Result: see the photo attached
![2 trash captured 2018-04-23 14 01 04](https://user-images.githubusercontent.com/38650029/39123003-2cecdbb2-46ff-11e8-98b7-73b8cf577d4c.jpg)

**Comment by lynxlynxlynx** [comment]
The second is my fault, giving more space to the subtitle. I'll just revert that now.
