### ISSUE TITLE
Cannot click on Create Trashpoint

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#230]
Create Trashpoint button not visible - first time happened on 27.04 - was working before.
Several tries - no result:
Android, Xiaomi Rebmi Note 4 & Android, Xiaomi MI A1

![31350822_592340924456246_454749737141141504_n](https://user-images.githubusercontent.com/30211382/39352898-cbb10e00-4a0e-11e8-9e43-d57348db5bc5.png)

**Comment by KristiinaKerge** [comment]
can you please ask to test it.

note that the application currently runs on Android 5.0 or newer versions of the operating
system.
