### ISSUE TITLE
[Offline build] [Both] Performance issues 

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#235]
**Devices:** SGS7 7.0, SGS4, iPhone 7+ 11.3.0, iPhone 6
**Preconditions:**
App was created and built from master branch. Release build

**Steps to reproduce:**
Login to the app
Check trashpoints map, my activity tab, photos in trashpoint details.

**Actual result:**
List is shown with delay, photos are not always shown, trashpoints on the map

**Comment by lynxlynxlynx** [comment]
Sounds like something that will get fixed by the backend migration to a more performant VM.

**Comment by lynxlynxlynx** [comment]
Yeah, same small delays can be seen in the web app. So I highly doubt this is related to the mobile apps, even less offline mode.
