### ISSUE TITLE
[Offline build][iOs] Pins on trashpoints map are too large 

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#239]
Device: iPhone 6
Preconditions:
App was created and builded from master branch. Release build
Steps to reproduce:
Start the app
Check map screen

Result:
trashpoints pins and current position pins are really large  http://take.ms/B2CTg
Is not reproducing on Android ( till it was working)
![movie recording 2018-05-10 17-01-38](https://user-images.githubusercontent.com/15016798/39873540-e7b820d8-5473-11e8-96de-554f75489308.png)

**Comment by lynxlynxlynx** [comment]
Could be the platform deducts the wrong size and uses too big an image. Eg. using ./mobile-app/src/components/Map/images/pointer_threat@3x.png vs ./mobile-app/src/components/Map/images/pointer_threat@2x.png or the original.
