### ISSUE TITLE
Create translations for new languages

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#24]

**Comment by android-labtech** [comment]
I can help for Italian Traslation.

**Comment by krishaamer** [comment]
Awesome @android-labtech! Thanks! For now there's this file you can base your translations on https://github.com/letsdoitworld/World-Cleanup-Day/blob/master/mobile-app/src/trans/en.json and soon we'll hopefully move such tasks to https://crowdin.com/ to ease the collaboration.

**Comment by kadry55** [comment]
Should be sent to all country teams

**Comment by krishaamer** [comment]
@android-labtech I've now setup Crowdin so you can join the translation team here: https://crowdin.com/project/world-cleanup-day

**Comment by lynxlynxlynx** [comment]
Crowdin is not mentioned anywhere in the repo:
https://github.com/letsdoitworld/World-Cleanup-Day/search?q=crowdin

while we could change the readme and other docs, github is not really friendly for non-technical people, so I think it's better we first add the key links to the Map it page.

**Comment by lynxlynxlynx** [comment]
New languages at 100% (app) were enabled today: 
> albanian (sq), belarussian (be), cebuano (ceb), dutch (nl), estonian (et), 
> fillipino (fil), greek (el), hungarian (hu), italian (it), lithuanian (lt), 
> polish (pl), portuguese (pt), romanian (ro), slovenian (sl), tagalog (tl), 
> ukrainian (uk), vietnamese (vi)

Left out:
- arabic (RTL — status unknown), 
- pt_br, traditional chinese (zhtw), arabic sa (arsa) — no files, need to fix crowdin config first and rename files

Existing enabled languages: English, Spanish, French, Russian, Chinese Simplified, Hindi, Indonesian

**Comment by lynxlynxlynx** [comment]
... and somehow I missed Norwegian and Turkish, which are now also enabled.
