### ISSUE TITLE
[Offline build] [Both] Not all trashpoints (only one out of 3) are saved in offline mode

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#241]
**Devices:** SGS7 7.0, SGA3 7.0, iPhone 7+ 11.3.0, iPhone 5 SE 11.2.2
**Preconditions:**
App was created and built from master branch. Release build

**Steps to reproduce:**
Login to the app 
Turn off the internet
Create 3 trashpoints in offline mode
Restore internet connection → check how many trashpoints were saved

**Actual result:** ONLY ONE trashpoint (out of 3) was saved which were created in offline mode.

**Comment by lynxlynxlynx** [comment]
Were they created at the same location?

**Comment by darjalsk** [comment]
In the offline mode user cannot choose location -> he can select another location only when the internet connection is restored. So, the answer is yes, they were created at the same location in the offline mode.

**Comment by lynxlynxlynx** [comment]
What, that's absurd!? The position should only depend on the GPS readout. Are you sure we're talking about the same thing?

**Comment by darjalsk** [comment]
I meant the same thing that you said. The position in offline mode depends on the GPS readout that's right -> and yes the trashpoints were created in one place using the same location. 
Before it was working fine, user could create several trashpoints in offline.

**Comment by lynxlynxlynx** [comment]
So are you saying movement isn't detected? We actually like the fact that you can't report several points at the exact same location. But of course the user would have to be notified if he tried, primarily it's more about preventing exact duplicates due to api misuse.

**Comment by Dasha1990** [comment]
Sorry, perhaps there is some misunderstanding. Do we have some verification which prohibits to create several trashpoints with same coordinates? It was possible earlier

**Comment by lynxlynxlynx** [comment]
I don't think we do yet. What I'm saying is that if this bug is not reproducible with variable locations, then it is more of a feature request.
