### ISSUE TITLE
Tapping a cluster doesn't zoom in fast enough

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#25]
If you look at the Oslo data or the Belgian 4, you have to tap too many times to get anywhere. The Belgian example zooms you in to an absurd level before the cluster is split. Could be duplicated reports, but the Oslo data also makes it obvious.

Starting with zoomed out Europe, I see a cluster of 15 over Norway. I have to click it some 7 times before it is split into subclusters. I expected to be taken to that zoom level immediately, upon first click.

As a sidenote, related to #5, the cluster position keeps jumping around on the map when you're zooming.

**Comment by kadry55** [comment]
We are checking all the issues that are open. Unfortunately this cannot be tested as the app servers are down. Should be checked again next week.

**Comment by lynxlynxlynx** [comment]
This also seems to have been fixed by duplicate removal. The case in the sea of Oslo is still visible, as the points aren't exact duplicates, but that's it. Priority is definitely lower.

**Comment by lynxlynxlynx** [comment]
Seems to be ... though there's now a different bug present (no more spidering when tps are too close).
