### ISSUE TITLE
[Offline] Admin can create trashpoint out of 100m range

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#250]
**Device:** Nexus 6P 8.1.0, SGS7 7.0, iPhone 6 11.3.1
**Pre-conditions:**
App was created and built from master branch. Release build

**Steps to reproduce:**
    1. Log in the app as an admin (location allowed)
    2. Turn off Wi-Fi -> create trashpoint in offline mode
    3. Try to change location

**Actual result:** Admin can create trashpoint out of 100m range (anywhere on the map, no restrictions).

**Comment by KristiinaKerge** [comment]
@darjalsk yes, it is not bug, it has to be so

**Comment by lynxlynxlynx** [comment]
That's expected behaviour, admins have this freedom. Though I admit I don't see this check in the mobile code for creation, only editing, so no idea how it succeeded.
