### ISSUE TITLE
Offline notification looks like an error message

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#256]
I have received reports that Offline notification looks like an error message and people stop using the app when seeing it:
![33653529_1253021091494636_937948044865830912_n](https://user-images.githubusercontent.com/30211382/40577679-385fa844-6112-11e8-8f53-3a905cb8fe16.jpg)

**Comment by lynxlynxlynx** [comment]
The title is "no network connection". I suggest we change the texts to:
Welcome to offline mode! 
Continue mapping as before. The trashpoints will be sent to the map server as soon as you regain Internet access.

(and the coordinates are deliberately rounded, phew)

**Comment by kadry55** [comment]
This sounds much more welcoming :)
