### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [letsdoitworld/World-Cleanup-Day#259]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and we already have a Request For Packaging this app [here](https://gitlab.com/fdroid/rfp/issues/396).

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by lynxlynxlynx** [comment]
I see no issue, for us it'd be another channel to potentially reach a few more users. How much work does it entail to update it there with each release? And yes, if someone else takes it over, that much simpler for this chaotic project.

**Comment by Poussinou** [comment]
Oops I didn't see that : you're using Google Maps, which is obviously not free-as-in-freedom.
F-Droid needs to build everything from source, and every dependencies for the project should also be free. Not sure we can include this in F-Droid.

@rudloff What do you think?

**Comment by Rudloff** [comment]
Indeed, react-native-maps depends on Play services: https://github.com/react-community/react-native-maps/blob/9ddd7a0d75a16b21c8561461fbee4d5e55040ebd/lib/android/build.gradle#L47
This is a non-free library so we can't include it in F-Droid unless the app can be built with a different map provider.

(There is a react-native-maps issue about this: https://github.com/react-community/react-native-maps/issues/712)

**Comment by lynxlynxlynx** [comment]
Indeed. There are some ideas to provide alternatives eventually, both to be able to display the map offline and to display it everywhere. But this is not something that will happen this year, if at all. So, I'll close this for now. Thanks for looking into it!
