### ISSUE TITLE
Severe error for the Mobile App

### ISSUE THREAD

**Issue by chimayscripteur** [letsdoitworld/World-Cleanup-Day#261]
Just reporting a severe error to make sure it is known by the community.

The App doesn't load anymore and the end-users receive the following error message on a blue screen:
> Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

Kind regards,

**Comment by KristiinaKerge** [comment]
Thank you for the report.

We are aware of the problem and working on it to solve the issue with Android app.

**Comment by KristiinaKerge** [comment]
The issue is fixed.
