### ISSUE TITLE
[Teams] 500 at joining team

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#263]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:

1. Log in to the app as volunteer
2. Open Profile
3. Search for some team
4. Try to join team

Expected result: user can join the team
Actual result: 500 error is shown  http://take.ms/y6M5U
request is PUT /api/v1/me/team HTTP/1.1
request body {
    "team": "3b61c81a-2b8e-11e8-b467-0ed5f89f717e"
}
response is 500 [{
    "code": "API_UNEXPECTED_ERROR",
    "message": "An unexpected error has occured."
}

also there is teams counter and it changes its value as if user really joined team

**Comment by KristiinaKerge** [comment]
high priority @aleksandr-wemakesoftware

**Comment by Dasha1990** [comment]
db_1       | 2018-06-06T15:18:27.321Z - fatal: SENECA: [CRASH] role:db,cmd:modifyOwnUserProfile {"update":{"team":"3b61c81a-2b8e-11e8-b467-0ed5f89f719j","updatedAt":"2018-06-06T15:18:27.285Z","updatedBy":"facebook:929766000507542"},"role":"db","cmd":"modifyOwnUserProfile","transport$":{"track":["d2wvmhat5rzt/1528294822468/356/3.4.1/-"],"origin":"d2wvmhat5rzt/1528294822468/356/3.4.1/-","time":{"client_sent":"1528298307246"}},"id$":"7cdtm6yvzqt7/tz3uz6ou29de","fatal$":false,"tx$":"tz3uz6ou29de"} // TypeError: Cannot create property 'members' on boolean 'false'
db_1       |     at Connector.<anonymous> (/src/plugins/accounts.js:167:46)
db_1       |     at <anonymous>
db_1       |     at process._tickCallback (internal/process/next_tick.js:169:7)
api_1      | 2018-06-06T15:18:27.330Z - error: Error: 
api_1      |     at module.exports.internals.Utils.internals.Utils.handle_response (/module-service-factory/node_modules/seneca-transport/lib/transport-utils.js:71:11)
api_1      |     at /module-service-factory/node_modules/seneca-transport/lib/http.js:154:25
api_1      |     at internals.Client._shortcut.callback.request.read (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:514:20)
api_1      |     at finish (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:360:16)
api_1      |     at wrapped (/module-service-factory/node_modules/hoek/lib/index.js:871:20)
api_1      |     at module.exports.internals.Recorder.onReaderFinish (/module-service-factory/node_modules/seneca-transport/node_modules/wreck/lib/index.js:406:16)
api_1      |     at Object.onceWrapper (events.js:314:30)
api_1      |     at emitNone (events.js:110:20)
api_1      |     at module.exports.internals.Recorder.emit (events.js:207:7)
api_1      |     at finishMaybe (_stream_writable.js:579:14)
api_1      |     at afterWrite (_stream_writable.js:431:3)
api_1      | 2018-06-06T15:18:27.331Z - warning: Error undefined was masked in the API response as API_UNEXPECTED_ERROR.
api_1      | 2018-06-06T15:18:27.332Z - HTTP: [RESP] 217.20.178.57 PUT /api/v1/me/team 500 78 - 273.770 ms
