### ISSUE TITLE
[Teams list] Possible to search local teams from another country 

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#264]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:

Log in to the app as volunteer
Open Profile
Search for some team
Check teams list

Expected result:  volunteer should see only teams with same country as in his profile + global teams in search results
Actual result: volunteer can see global and all local teams in search results 
http://take.ms/gCRHv

**Comment by KristiinaKerge** [comment]
we can go live with it, low priority
