### ISSUE TITLE
[Teams] Missing placeholder with nothing found state

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#267]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:

1. Log in to the app as volunteer
2. Open Profile
3. Search for team name that doesn't exist
4. Check screen

Expected result: nothing was found state placeholder is shown
Actual result: same placeholder as if search wasn't performed is shown http://take.ms/kFQPz

**Comment by KristiinaKerge** [comment]
solved in new version, released in July 11
