### ISSUE TITLE
[Teams] Even global teams have "nationalTeam": true parameter

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#268]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:

1. Log in to the app as volunteer
2. Open Profile
3. Search for team "friends"  | GET /api/v1/teams?country=UA&search=Friends HTTP/1.1
4. Check team details
[{
	"name": "Friends of World Cleanup Day",
	"teamDescription": "If you believe that World Cleanup Day is a wonderful initiative which you want to support, then this team is for you! Map the waste so we can end trash blindness once and for all!",
	"image": "https://ucarecdn.com/069167ae-5519-475b-a6bf-69bee37a1200/Reddie.png",
	"nationalTeam": true,
	"createdAt": "2018-06-05T13:06:04.773Z",
	"id": "3b61b794-2b8e-11e8-b467-0ed5f89f718b",
	"members": 0,
	"trashpoints": 0,
	"lastTrashpoints": [],
	"groupCount": {}
}]

Expected result: global team has flag "nationalTeam": false, as Kristiina Kerge said "it shows is it a global team or not"

Actual result: global team has flag "nationalTeam": true,

**Comment by lynxlynxlynx** [comment]
No team in the live db has that flag set to false. @KristiinaKerge do we have an up-to-date list of only global teams somewhere?

**Comment by KristiinaKerge** [comment]
no need to hide country teams as users can't change their country in the app

**Comment by lynxlynxlynx** [comment]
Actually they were imported as such and it somewhat makes sense — for a filtered listing one would display all nationalTeams where the country is unset or equals the user one. Saves one query.
