### ISSUE TITLE
[Teams] [Web] Country admin can't get teams list (admin country name is sent as undefined in request)

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#272]
Google Chrome Version 66.0.3359.181
Pre-conditions:

Steps to reproduce:

Log in to the web app as country admin
Open teans list
Check results

Expected result: there is teams list
Actual result: there is no any team, request is returned with 400 error bad request because wrong country is sent http://40.115.37.120:50000/api/v1/teams/web?country=undefined&superadmin=false
http://take.ms/0zQc5

**Comment by KristiinaKerge** [comment]
Admin can see only teams from his country. Superadmin can see all teams

**Comment by KristiinaKerge** [comment]
@Dasha1990 can superadmin see all teams in admin web

**Comment by Dasha1990** [comment]
@KristiinaKerge yep, super admin can see all teams http://take.ms/f2eCj

**Comment by Dasha1990** [comment]
@aleksandr-wemakesoftware here you can see how user gets list of world cleanup day app users for Estonia (as he is Estonian country admin) and EE is sent as country code
Below you can see request for teams where country code is not sent 
http://take.ms/uQphC
http://take.ms/3cwRK

**Comment by Dasha1990** [comment]
Checked country admin after login in mobile app. 
After login in mobile app country is saved to user profile.
During work as country admin requests for teams are sent with country saved in user profile NOT with area/county assigned to admin http://take.ms/Ni95U
