### ISSUE TITLE
[Team details] Missing trashpoints statistics in Latest activity/trashpoints counters

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#273]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:

Log in to the app as volunteer
Open Profile
Join some team
Create trashpoint
Open team details 
Check Latest activity and trashpoints counter

Expected result: user can see new trashpoint statistics
Actual result: there is no trashpoints in latest activity/updated trashpoints counters

**Comment by KristiinaKerge** [comment]
This is critical, we have to solve it
