### ISSUE TITLE
[Teams] Team's profile details are missing

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#274]
**Device:** iPhone 8+ 11.3.1
**Pre-conditions:** Release build, branch hotfix/blue_screen

**Steps to reproduce:**
Log in to the app as volunteer
Open Profile
Join a team -> create a trashpoint
See team profile's details

**Actual result:** Team's profile details are missing: Team's trashpoints, latest activity, members view. 
![act 2018-06-07 17 05 12](https://user-images.githubusercontent.com/38650029/41104918-2c7cc522-6a75-11e8-9d4e-8b12faf00843.jpg)

**Expected result:** All team's profile details are present and functional. 
![exp](https://user-images.githubusercontent.com/38650029/41104924-30a58db4-6a75-11e8-90ec-158aaa8c2aeb.jpg)

**Comment by KristiinaKerge** [comment]
The view team members option is not relevant, we left it out
