### ISSUE TITLE
[Create trashpoint] User can create trashpoint without a picture

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#277]
**Device:** iPhone 8+ 11.3.1
**Pre-conditions:** Release build, branch hotfix/blue_screen

**Steps to reproduce:**
Log in to the app as volunteer
Create a trashpoint without photo

**Actual result:** User can create a trashpoint without a picture.
**Expected result:** User cannot create a trashpoint without a picture.

**Comment by KristiinaKerge** [comment]
is it fixed in new version @darjalsk

**Comment by darjalsk** [comment]
It was fixed. User cannot create a trashpoint without a picture.

**Comment by KristiinaKerge** [comment]
fixed
