### ISSUE TITLE
UX: Improvements of login screen

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#28]
* Background looping video
* Align Terms & Conditions and Privacy Policy to bottom
* increase space between buttons and tryout link

**Comment by KristiinaKerge** [comment]
new logo (full version with figure) https://www.dropbox.com/s/l67bny38bvememb/cleanup.sketch?dl=0 https://drive.google.com/open?id=0B-AbsGblifS-dkVpMFlfX2Q0Yjg

**Comment by sebid** [comment]
If the T&C and Privacy Policy links are aligned to the bottom they might not show up for certain devices.
For example, on an iPhone 5/5S/SE, these links may appear cut off if they are moved to the bottom.

**Comment by rionita** [comment]
estimate: 4h

**Comment by krishaamer** [comment]
Link to video asset: https://www.dropbox.com/s/wpk2v6osoky5c3c/phone_bg_s.mov?dl=0

**Comment by rionita** [comment]
development done, needs to be tested
