### ISSUE TITLE
[Teams] Teams screen is updated only at app restart

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#282]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:

1. Release build, branch hotfix/blue_screen
2. You will need two users and two devices to reproduce this issue
3. Login to the app with both users
4. Join same team with both users

Steps to reproduce:
1. Create trashpoint with user A while user B is still in the app
2. Open team profile and check trashpoints statistics

Expected result: user B can see added trashpoints counter in team details
Actual result: user B can't see new trashpoint counter with updates of user A till he start app again

**Comment by KristiinaKerge** [comment]
is it solved in new version @Dasha1990 @aleksandr-wemakesoftware

**Comment by Dasha1990** [comment]
currently teams statistics is updated on every team opening
