### ISSUE TITLE
[Teams] ONLY 4 first trashpoints are always shown in Latest activity

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#283]
Device: Samsung S4 note 6.0.1, htc 5.0.1
Pre-conditions:
Release build, branch hotfix/blue_screen

Steps to reproduce:
Log in to the app as volunteer
Join the team
Create five trashpoints
Check trashpoints statistics

Expected result: 4 last trashpoints are shown
Actual result: 4 first trashpoints are shown

**Comment by KristiinaKerge** [comment]
all trashpoints are visible in list view in new version, released July 11. 
With volunteers help or with next funding we can improve the list and make the trashpoints clickable.
i close this issue as it was releated with expo version
