### ISSUE TITLE
[Team] White screen and loader are shown at app start ( sometimes really long)

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#286]
Device: Samsung S4 note 6.0.1, htc 5.0.1

Steps to reproduce:
Start the app
Check screen

Expected result: there is empty white screen with loader shown really quickly and app starts

Actual result: there is empty white screen with loader shown for a long time and sometimes app stuck

**Comment by KristiinaKerge** [comment]
it is fixed with new version, released July 11
