### ISSUE TITLE
[Teams] Missing translations 

### ISSUE THREAD

**Issue by darjalsk** [letsdoitworld/World-Cleanup-Day#291]
Here is the list with missing translations for **Teams**.

- label_text_my_team is unused in code
- translated status strings are not used in the teams view: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated
-  “How to increase your impact” is still hardcoded

----------

**All translations**. Missing label in crowdin for “How to increase your impact”

**english** – yes

**spanish** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**french** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**russian** 
missing all translations

**chinese simplified** 
missing all translations

**hindi** 
missing all translations

**indonesian** 
missing all translations

**albanian(sq)** 
missing all translations

**belarussian (be)** 
missing all translations

**cebuano (ceb)** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**dutch (nl)** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**estonian (et)** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**fillipino (fil)** 
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**greek (el)** 
missing all translations 

**hungarian (hu)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**italian (it)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**lithuanian (lt)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**polish (pl)**
missing all translations

**portuguese (pt)**
missing all translations

**romanian (ro)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**slovenian (sl)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**tagalog (tl)**
can’t find in device settings

**ukrainian (uk)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**vietnamese (vi)**
missing translation for > label_text_my_team. 
Trash statuses: label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**norwegian**
missing all translations

**turkish** 
missing all translations

Also missing translations for team description/global/city/teams names:
**japanese** missing translation for > label_text_my_team. Also missing translations for team description/city/teams names
label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated

**faroese** missing translation for -> label_button_leave_team -> label_header_team_profile -> label_text_my_team
label_trash_status_threat  -> label_trash_status_regular -> label_trash_status_cleaned -> label_trash_status_outdated
Also missing translations for team description/global/city/teams names.

**Comment by lynxlynxlynx** [comment]
By "missing all translations" you mean missing all TEAM translations? You say that for Slovenian, for example, but the app is still translated for me and team stuff too.

One other untranslatable thing is the statuses in team stats

**Comment by Dasha1990** [comment]
In this ticket we mentioned only stuff connected to Teams screens. 

Regarding Slovenian - my bad, I found that language is called slovenščina but there is two kinds of them. For Slovenian there are missing parts of translations. Issue description was updated with that info.

**Comment by Dasha1990** [comment]
yeah :)
but I guess its better to add statuses translations to team details too

**Comment by lynxlynxlynx** [comment]
I'll edit the main post to list the actionables.

**Comment by lynxlynxlynx** [comment]
Redundant in this version.
