### ISSUE TITLE
[Web][Teams] Filters by users/score is not working

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#292]
Chrome
Steps to reproduce:

1. Log in to the web app as super admin
2. Open teams list
3. Tap on filter by users/score

Expected result: there is no filters mentioned in specification/design, perhaps we can hide them for now?
Actual result: filters via users/score is not working

**Comment by lynxlynxlynx** [comment]
filtering is gone.
