### ISSUE TITLE
Issue with logging in - iPhone

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#293]
1- I have I phone 6s with updated software 
2- yes I updated the App to the newest version 
3- there is no error occurring, the problem is that when I entered the FB password to login the App, the App take me again to the main page without login, I tried to log in using google, same problem, no login and it takes me again to the main page
4- attached the screen shot (just a login page)
5- I am currently located in Lebanon and yes the same problem with many other people

**Comment by lynxlynxlynx** [comment]
the ios version is still the old version, as there are delays in fruit acceptance of our work.
