### ISSUE TITLE
[React native] clustering vs zoom issue

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#303]
If you look at the Czech republic, there's a cluster with 2 points in the NE visible at first load.

If you click on it to zoom in:
- it doesn't expand the cluster
- so naturally you click again, but soon that just leaves you with an empty map and "Search here" doesn't find anything

The first bit is the real issue, the second is correct — the two points are already out of the viewport.

**Comment by Dasha1990** [comment]
We checked this behavior and went to conclusion that this logic is affected by weak performance of stage server, as we plan this won't be spotted on production

**Comment by KristiinaKerge** [comment]
is it fixed @Dasha1990 @lynxlynxlynx
