### ISSUE TITLE
[React native] can't add trashpoint — no type&origin selector

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#304]
DOM is basically empty:
![spectacle ib6672](https://user-images.githubusercontent.com/121515/42047142-c5075718-7aff-11e8-8637-492c55b1b9df.png)
![spectacle eq6672](https://user-images.githubusercontent.com/121515/42047180-e0013a66-7aff-11e8-9bfb-225a6137af74.png)

**Comment by Dasha1990** [comment]
That's a known issue, we are tracking it in our jira now
