### ISSUE TITLE
[React native] 400 bad request when trying to inspect country

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#305]
Clicking on the list of countries (users tab):

> GET https://api-staging.app.worldcleanupday.com/api/v1/users?pageNumber=1&pageSize=20&country=AS 400 (Bad Request)

> [{"code":"SWAGGER_REQUIRED","message":"Request validation failed: Parameter (userRole) is required"}]

Same for trying to search
> GET https://api-staging.app.worldcleanupday.com/api/v1/users?pageNumber=1&pageSize=20&country=AF&nameSearch=slove 400 (Bad Request)

**Comment by Dasha1990** [comment]
yep, that's known issues connected to prioritising users in the list
