### ISSUE TITLE
[React native] country list not scrollable

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#306]
Maybe a design decision, but definitely unintuitive. From an API pow, there's no way to get to page 2 and onwards.

**Comment by Dasha1990** [comment]
AS I understand we are talking about web app and there is no pagination for countries request GET /api/v1/areas  http://take.ms/bgdpc. Also I'm able to scroll it in me chrome/safari. if this list is not scrollable in your browser, can you please share its name/version?

**Comment by lynxlynxlynx** [comment]
It was with Chromium 66.0.3359.181. I don't have access to the country list anymore though, so can't test what changed in the meanwhile.
The list was scrollable, but only within the first page — you can't scroll to the rest if it's meant to be an infinite scroll.

**Comment by Dasha1990** [comment]
Can you please share your email so we can make you a super admin in stage DB again? 
We have an issue connected to countries list - there are not all countries currently shown, we also track it in our jira.
