### ISSUE TITLE
[React native] country list missorted

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#307]
> Azerbajdan
> Bahamas
> ...
> Belarus
> Åland

So it's not sorting with unicode in mind, as Åland should come earlier — with the "A"s. Eg.
```
$ echo -e "BEEE\nAjaja\nBBBB\nÅållll\nAAA" | sort
AAA
Åållll
Ajaja
BBBB
BEEE
```

**Comment by Dasha1990** [comment]
yep, that is known issue, we track it in our jira
