### ISSUE TITLE
(Web)(Admin) Admin cannot see user information of trashpoints since the new release

### ISSUE THREAD

**Issue by kadry55** [letsdoitworld/World-Cleanup-Day#322]
Admin should see all the users information in his/her country. Superadmin should see all users information.

![image](https://user-images.githubusercontent.com/30211382/42988234-8a3588d8-8c04-11e8-815f-e7f26463d5d8.png)

**Comment by Dasha1990** [comment]
Valera is working in this fix now

**Comment by lynxlynxlynx** [comment]
This has been fixed and deployed already.
