### ISSUE TITLE
Trash point is created more than once because after pressing save trash point nothing happens

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#33]

**Comment by KristiinaKerge** [comment]
I tested it in web app and same problem. I added one trashpoint, saved only once but created 3 trashpoints. I deleted them

**Comment by rionita** [comment]
estimate: 4h

**Comment by krishaamer** [comment]
OK.

**Comment by kadry55** [comment]
Described also in #129  for  admin web

**Comment by rionita** [comment]
development in progress

**Comment by lynxlynxlynx** [comment]
So there's several issues open for related stuff. I propose this one remains as a UX problem, if it is still present and #73 tracks actual duplication prevention.
