### ISSUE TITLE
Investigate upgrade to expo sdk version 20.0.0

### ISSUE THREAD

**Issue by stochris** [letsdoitworld/World-Cleanup-Day#4]
The project currently uses the expo sdk version 19.0.0. According to their [release](https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1) announcement, there are no breaking changes.
However, the new version uses a different version of react-native, and it should be investigated.

Also, it might fix issues with the `ImagePicker` on lower versions of android ( 4.4 )

**Comment by KristiinaKerge** [comment]
New version, released 10 July 2018, doesn't have expo.
