### ISSUE TITLE
Better size consistency across phone sizes

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#41]
* icons
* text
* left design vs right app

![image3](https://user-images.githubusercontent.com/54409/30960890-1e1b6e00-a44d-11e7-847c-19c0e51091c3.png)

![image2](https://user-images.githubusercontent.com/54409/30960889-1e187650-a44d-11e7-9bd4-eb913c5afa96.png)

**Comment by krishaamer** [comment]
What about this one @rionita ?

**Comment by krishaamer** [comment]
Same as https://github.com/letsdoitworld/World-Cleanup-Day/issues/6

**Comment by rionita** [comment]
we need to align icon sizes and alignment to the design, as specified in the initial comment
