### ISSUE TITLE
What is sync period on map (when no action is taken) to see new TPs?

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#49]

**Comment by kadry55** [comment]
Map in app and admin web is not updating itself fast enough. In order to see African TPs (when zooming out from Europe to world level), i have to zoom in to Africa.

**Comment by rionita** [comment]
Seems there isn't any auto-sync. The map syncs only when you pan around it.

**Comment by KristiinaKerge** [comment]
in new version we have "Search this area" and if there are no trashpoint in the area we show notification 
![screenshot_20180716-111926](https://user-images.githubusercontent.com/26063413/42748843-41a8c84a-88ea-11e8-8fdc-426dc0b7ca8b.png)
