### ISSUE TITLE
UX: Add scroll down arrow after photo is taken?

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#52]
When choosing between two icons threat and regular I am waiting for something to happen. I forget to scroll down. This has been reported also by other users.

**Comment by krishaamer** [comment]
Same as https://github.com/letsdoitworld/World-Cleanup-Day/issues/9

**Comment by KristiinaKerge** [comment]
@rionita please give an estimate to it

**Comment by KristiinaKerge** [comment]
from Kadri, 6 Sept, issue #9 : When choosing between two icons threat and regular I am waiting for something to happen. I forget to scroll down. Add down slider indicator or other method to indicate additional information is below “point status.” Tried swiping left/right and then clicking on orange “regular” button before realizing it went down. It’s easy to determine but need something to indicate. Know this may be clear on other screen sizes.

**Comment by kadry55** [comment]
No scrolldown arrow can be seen

**Comment by KristiinaKerge** [comment]
In new design the amount icons are placed so that user will tap on the screen and after the tap they will see scrollbar on the side.
