### ISSUE TITLE
Post trashpoints anonymously 

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#64]

**Comment by KristiinaKerge** [comment]
web lite will allow users to report trash points without log in https://trello.com/b/ibpdZNCa

**Comment by KristiinaKerge** [comment]
related with #100

**Comment by KristiinaKerge** [comment]
new version allows users to keep their profile private. By default the profile is private and all trashpoints reported with private profile will be anonymous. If user turns profile public then all previous and next trashpoints will have user name on it

**Comment by kadry55** [comment]
User should see the trashpoints reported before new functionality when profile is not anonymous

**Comment by KristiinaKerge** [comment]
Please specify see where and what trashpoints.
Is it related anonymous reporting?
