### ISSUE TITLE
GPS coordinates taken from the photo

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#68]

**Comment by kadry55** [comment]
In admin web when admin is adding a photo that is sent from a user, it would reduce work tremendously if the coordinates were taken from the photo.

**Comment by lynxlynxlynx** [comment]
I can add this if nobody is working on it. Let me know.

**Comment by KristiinaKerge** [comment]
@lynxlynxlynx nobody is working on it

**Comment by lynxlynxlynx** [comment]
Ok, I'll take a look. But first to set up the dev environment ...

**Comment by lynxlynxlynx** [comment]
The first hurdle is gone and I have  the web app running (will end up as some docs for #2). However it's not clear how to log in now. The FB/Google options of course don't work, since this is a local instance. And from a few simple searches, I didn't find any overrides. There's no docs either, so @KristiinaKerge  please ask whomever is appropriate about it. I can't test my code without getting into the admin backend and it would be silly to try to hack around it.

**Comment by rionita** [comment]
hi @lynxlynxlynx, please make sure you are following all the instructions found in the following readme's:
- https://github.com/letsdoitworld/World-Cleanup-Day/blob/master/devops/dev/README.md
- https://github.com/letsdoitworld/World-Cleanup-Day/tree/master/web-app
Google login should work if docker-compose was executed successfully.

**Comment by lynxlynxlynx** [comment]
Ah, thanks, didn't see the container setup. I have it running now, all backends are up and working, however on a fresh npm start the login situation is the same — both oauth providers complain my hostname is not an origin on their authorized list.

**Comment by lynxlynxlynx** [comment]
Tryed on a different machine, probably different basic dependency versions, but still the same problem.

**Comment by lynxlynxlynx** [comment]
Anyway, I have the code for this for a while now, just can't do the final integration and testing.

**Comment by KristiinaKerge** [comment]
can you please do the pull request

**Comment by lynxlynxlynx** [comment]
It'd be silly to do it blind, I can't vouch for that.

**Comment by krishaamer** [comment]
@lynxlynxlynx I think it's fine to do this in a dev branch so we can see the code and some else can help with testing.

**Comment by lynxlynxlynx** [comment]
There you go.  ¯\_(ツ)_/¯
