### ISSUE TITLE
Trashpoint size slider improvement

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#7]

**Comment by rionita** [comment]
estimate: 10h, but we will need more detailed requirements.
Depending on requirements, this estimate can change.

**Comment by krishaamer** [comment]
Invited you to https://projects.invisionapp.com/d/main#/console/10062817/239132414/preview

Requirements: 
The slider is currently only clickable - it should be slidable with your finger.

**Comment by rionita** [comment]
development done, needs testing
