### ISSUE TITLE
App asked for permission for location. It freezed. The permission wasn't given. The user had to go to settings and give the permissions manually

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#77]
App got stuck after the question to show location on map. She pushed yes - nothing happened. App didn't start (white screen before login screen). She uninstalled and then installed and then had same problem. Then opened GPS settings and saw that GPS didn't go in. Put it in manually and app started. Didn`t recieve a notification when app was not able to start the GPS.

**Comment by krishaamer** [comment]
Could not reproduce. Added logging.

**Comment by kadry55** [comment]
this happened on the first activation after installation.

**Comment by kadry55** [comment]
On  Sony Xperia XZs (Android 7.1.1)

**Comment by KristiinaKerge** [comment]
ok with Sony Xperia F5321, android 7.1.1

**Comment by kadry55** [comment]
ok with Samsung S6 edge

**Comment by KristiinaKerge** [comment]
ok with Sony Xperia XZs (Android 7.1.1)
