### ISSUE TITLE
Network error while having Internet connection

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#81]
Several time: Network error - no internet connection. Though there was LTE coverage and all other apps and web worked perfectly well. Error message comes when you have made a photo and pressed OK. Then in a minute it disappears (no option to press OK) but app is frozen. When you press back during that 1 minutes then you get back on map but its darkened and frozen - no option to do anything on screen).

**Comment by krishaamer** [comment]
Added logs

For acceptance;
Action Plan (26 sep 2017):
1. Deploy logging to production tomorow morning, 27 sep 2017
2. Monitor for loggs for the issue during the day, 27 sep 2017
3. Identify issue and propose the plan to fix it (updates latest on 28 sep 2017)

**Comment by KristiinaKerge** [comment]
Network error while having connection. https://drive.google.com/open?id=0B-AbsGblifS-RVllaW9CNDlMTEpzMEZyNFJiNDZOZi16VEdR

**Comment by KristiinaKerge** [comment]
app freezes, force stop helped

**Comment by krishaamer** [comment]
May be related to https://github.com/letsdoitworld/World-Cleanup-Day/issues/46

**Comment by krishaamer** [comment]
Can you confirm this was resolved @cprpopqual

**Comment by kadry55** [comment]
Comment from user on 5.12: These days I get this screen when I start the mapping app, it says that there isn't network connection, but there is network.

**Comment by KristiinaKerge** [comment]
I had the same problem 7.dec

**Comment by KristiinaKerge** [comment]
I got it on 27th of Dec after the login issue was fixed https://drive.google.com/open?id=0B-AbsGblifS-TlFaOWhyOGk5SS1qSnh4Sk5QUlpnc0tqNVY4

**Comment by KristiinaKerge** [comment]
@rionita @danieljirca-q do you have Identified the issue and do we have the plan to fix it

**Comment by kadry55** [comment]
This is from today:
![screenshot_20171228-104101](https://user-images.githubusercontent.com/30211382/34405414-ee521fe6-ebbb-11e7-8d5b-8625a2b45a69.png)

**Comment by rionita** [comment]
@KristiinaKerge: sorry for the late replies, but this is vacation period in Romania.
This happen sporadically and seems to be related (at a first glance) to a temporary loss of mobile data signal, or to the transition between either Wi-Fi and Mobile data or between mobile signal towers.

It does not further investigation, but this fix can't be easily estimated, since it's mainly research into the problem, there is no obvious fix that can be applied.

**Comment by kadry55** [comment]
The problem with this error is that it freezes the app for a while (1min): whereas with other errors you can just click on ok and continue (in most cases)

**Comment by KristiinaKerge** [comment]
fixed
