### ISSUE TITLE
Turning Internet off and on doesn't allow to create trashpoint

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#83]
When filling data about a pile if internet is off and then on the pile will not be created

**Comment by krishaamer** [comment]
Added logs

**Comment by KristiinaKerge** [comment]
Tested by Kristiina 30.oct - internet is on , added picture and type, turned internet off, shows on the screen no internet, turned internet on, clicked save and trashpoint was created

**Comment by kadry55** [comment]
Tested by Kadri 30.oct - internet is on , added picture and type, turned internet off, shows on the screen no internet, turned internet on, clicked save and trashpoint was created

**Comment by kadry55** [comment]
Fixed
