### ISSUE TITLE
When editing a pile detail and setting status from normal to clean and back from clean to normal you cannot save it because no new picture is added.

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#84]
The requirement says that the user needs to add a picture whenever the status is changed

**Comment by KristiinaKerge** [comment]
Tested by Kristiina, 31.oct - when editing a pile data I can click all statuses and if I finish with the status that was in the beginning and click save it doesn't ask for a picture
