### ISSUE TITLE
Map not loading on web app (location permission is given)

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#85]
On Safari
Map also not loading on Internet Explorer

**Comment by KristiinaKerge** [comment]
Tested by Kristiina - ok on Internet Explorer, Ping 8ms, download speed 147,81 Mbps, upload 20,98Mbps
Tested by Kadri - ok on Safari, Ping 9ms, download speed 3,7 Mbps, upload 3,6 Mbps
