### ISSUE TITLE
scroll down arrow after photo is taken

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#9]

**Comment by kadry55** [comment]
When choosing between two icons threat and regular I am waiting for something to happen. I forget to scroll down. Add down slider indicator or other method to indicate additional information is below “point status.”  Tried swiping left/right and then clicking on orange “regular” button before realizing it went down.  It’s easy to determine but need something to indicate.  Know this may be clear on other screen sizes.

**Comment by KristiinaKerge** [comment]
dublicate of #52
