### ISSUE TITLE
Server error 400 when opening the map

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#90]
User report:

The error ocured when I open the map, yesterday. Today at the morning was fine, no error, but I didn't try to use it as adding new trash point. Now at the moment I try to open the app, and it's white screen, it doesn't open at all. The device is Huawei number model CUN-L01 as I can see in the info.

![screenshot_20170927-112538](https://user-images.githubusercontent.com/54409/30990733-0721f530-a4ab-11e7-8d53-86d283d046f0.png)

Reported in Panama, Russia and Philippines.

**Comment by krishaamer** [comment]
Feedback from developers: "We figured out the problem, we're making a build that should fix it. It's due to the Expo framework"

**Comment by sebid** [comment]
This should have been fixed. It was due to how Expo caches builds, it would build on a medium it was not intended for.

**Comment by kadry55** [comment]
@krishaamer @KristiinaKerge This happens for me every day (especially when zooming). Should get a priority.

**Comment by kadry55** [comment]
This is from today. First got error 503 when logging in and when map opened then error 400 and after that No Network Connection though coverage is good here.
![screenshot_20171228-104101](https://user-images.githubusercontent.com/30211382/34405390-cb5467a6-ebbb-11e7-847c-576b46d71d2a.png)

**Comment by KristiinaKerge** [comment]
@rionita @sebid do you have identified the issue and do we have the plan to fix it?

**Comment by kadry55** [comment]
User report from Ecuador from 21 December 2017:
Error 400 when on map.
Yes, it happened more than once.
My phone model is: Samsung Galaxy J5 Pro
SW version: Android 7.0

**Comment by KristiinaKerge** [comment]
@kadry55 can they test it again
