### ISSUE TITLE
[Admin web] trashpoint links don't work correctly

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#99]
For example https://app.worldcleanupday.com/trashpoints/3e6df6d6-b780-4e40-b807-b420c78d169a should open a TP in Mauritius but the map shows my current location (even though the TP sidebar opens the correct data).

**Comment by lynxlynxlynx** [comment]
The URL doesn't update when you click on a tp, that's why.

**Comment by krishaamer** [comment]
@lynxlynxlynx They do when you're logged in as an admin however it still doesn't navigate to the right location.

**Comment by KristiinaKerge** [comment]
@rionita trashpoint link should work also without log in

**Comment by lynxlynxlynx** [comment]
MapView doesn't expose any method to update the viewport. Same underlying problem as #129, but just the underlying one.

**Comment by KristiinaKerge** [comment]
fixed
